### ISSUE TITLE
Clarifications Differential analysis vignette

### ISSUE THREAD

**Issue by maximelepetit** [saezlab/liana-py#118]
Hi !

I would like to explore interaction which the ligand is deregulated while the receptor is not, the opposite or such where they are deregulated in opposite directions.

I don't understand how can i deal it with ...

Can you help me ?

Thanks in advance.

Maxime

**Comment by dbdimitrov** [comment]
Hi @maximelepetit,

You should have that information in the `lr_res` - i.e. you can consider only the stats (e.g. logFC or p-values) of the ligand or receptor, rather than the interaction.

Is this what you mean? Or are you interested in basically also including opposite direction of change in your interaction ranking? In this case, you could e.g. compute a product of the logFC or Wald Statistics, which would give you something that you could sort the interactions by regardless if they are sign-consistent.

Hope this helps.
